### ISSUE TITLE
Correlate logs to traces

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit-datasource#34]
The elasticsearch plugin allows to define how to link a log to a trace. See the [datalinks](https://grafana.com/docs/grafana/latest/datasources/elasticsearch/) config part.

We should be able to have the same feature and provide this `dataLinks` configuration.

Here is a config example coming from the doc:

```yaml
      dataLinks:
        - datasourceUid: my_jaeger_uid # Target UID needs to be known
          field: traceID
          url: '$${__value.raw}' # Careful about the double "$$" because of env var expansion
```

To test the setup, we need 2 datasources: one quickwit datasource for the logs and one jaeger datasource for traces.
